import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  console.log(props.locale)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/" locale="ja">
          To /ja/
        </Link>
      </main>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: { locale },
  };
}
